# Generated by Django 4.2.5 on 2023-09-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=10)),
                ('harga', models.IntegerField()),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategori')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
        ),
    ]
