# Generated by Django 4.2.5 on 2023-09-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_status_nama_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(),
        ),
    ]
