# Generated by Django 4.2.5 on 2023-09-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_produk_nama_produk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='id_model',
            new_name='id_produk',
        ),
    ]
